// Code generated by "stringer -type=Pill"; DO NOT EDIT.

package enum

import "testing"

func TestPill_String(t *testing.T) {
	tests := []struct {
		name string
		i    Pill
		want string
	}{
		{
			name: "OK",
			i:    Aspirin,
			want: "Aspirin",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("Pill.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
